# ~/environment/sam-app/buildspec.yml

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install packages or any pre-reqs in this phase.
      - cd function-create
      - npm install
      - cd ..
      - cd function-delete
      - npm install
      - cd ..
      - cd function-retrieve
      - npm install
      - cd ..
      - cd function-retrieve-by-id
      - npm install
      - cd ..
      - cd function-update
      - npm install
  
  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.
      # npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
      - sam build

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - packaged.yaml
  discard-paths: yes